// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqnixgcovbiwbiixdytd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxbml4Z2NvdmJpd2JpaXhkeXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Njk2OTIsImV4cCI6MjA2MDI0NTY5Mn0.77YoF6czisNlZJVjk3XdD9RHnVfcx5CuhKHhbnFtdy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);